# Q1

In [ ]:
import numpy as np
import matplotlib.pyplot as plt


class hopfield:
    def __init__(self, dimens):
        self.weights = np.zeros((dimens, dimens))
        self.stablebool=False
        self.num=0
    
    def savedata(self, list_inps):
        list_inps = np.array(list_inps)
        listinps_rshp=list_inps.reshape(-1, 1)
        nweight = list_inps * listinps_rshp
        np.fill_diagonal(nweight, 0)
        self.weights += nweight
        print("Weight when its updated is : ", list_inps, " is changed to :\n", self.weights)

    def survey(self, inps_1):
        inps_1 = np.array(inps_1)
        sign_inps_1 = np.sign(np.dot(self.weights, inps_1))
        self.stablebool=(sign_inps_1 == inps_1).all()
        if (self.stablebool):
            print(inps_1, "stable")
        else:
            print(inps_1, "not stable, The closest stable data that saved is: ", sign_inps_1)
    def inps_stablizer(self, inps_1):
        inps_1 = np.array(inps_1)
        inps_1_r = inps_1.reshape(-1, 1)
        while(self.stablebool != True):
            nweight = inps_1_r * inps_1
            np.fill_diagonal(nweight, 0)
            self.weights += nweight
            input = np.array(inps_1)
            input_sign = np.sign(np.dot(self.weights, input))
            self.stablebool = (input_sign == input).all()
            self.num += 1
        print(f"{self.num} times this while worked to inps_stablizer the input")
        print(self.weights)

if __name__ == '__main__':
    
    hopf = hopfield(8)
    hopf.savedata([-1, -1, 1, -1, 1, -1, -1, 1])
    hopf.savedata([-1, -1, -1, -1, -1, 1, -1, -1])
    hopf.savedata([-1, 1, 1, -1, -1, 1, -1, 1])
    ##a
    #har se ok hastan

    hopf.survey([-1, -1, 1, -1, 1, -1, -1, 1])
    hopf.survey([-1, -1, -1, -1, -1, 1, -1, -1])
    hopf.survey([-1, 1, 1, -1, -1, 1, -1, 1])

    ####b

    hopf.survey([1, -1, 1, -1, 1, -1, -1, 1])
    hopf.survey([1, 1, -1, -1, -1, 1, -1, -1])
    hopf.survey([1, 1, 1, -1, 1, 1, -1, 1])
    ####c
    hopf.survey([1, -1, 1, -1, 1, -1, -1, 1])
    hopf.survey([1, 1, -1, -1, -1, 1, -1, -1])
    hopf.survey([1, 1, 1, -1, 1, 1, -1, 1])
    hopf.inps_stablizer([1, -1, 1, -1, 1, -1, -1, 1])
    hopf.survey([1, -1, 1, -1, 1, -1, -1, 1])
    hopf.inps_stablizer([1, 1, -1, -1, -1, 1, -1, -1])
    hopf.survey([1, 1, -1, -1, -1, 1, -1, -1])
    hopf.inps_stablizer([1, 1, 1, -1, 1, 1, -1, 1])
    hopf.survey([1, 1, 1, -1, 1, 1, -1, 1])

######inja natayej be soorat kamel neshhoon  dade nashode vali dar run kardan dar colab va dasti, hast.screen ham gharar dadam

Weight when its updated is :  [-1 -1  1 -1  1 -1 -1  1]  is changed to :
 [[ 0.  1. -1.  1. -1.  1.  1. -1.]
 [ 1.  0. -1.  1. -1.  1.  1. -1.]
 [-1. -1.  0. -1.  1. -1. -1.  1.]
 [ 1.  1. -1.  0. -1.  1.  1. -1.]
 [-1. -1.  1. -1.  0. -1. -1.  1.]
 [ 1.  1. -1.  1. -1.  0.  1. -1.]
 [ 1.  1. -1.  1. -1.  1.  0. -1.]
 [-1. -1.  1. -1.  1. -1. -1.  0.]]
Weight when its updated is :  [-1 -1 -1 -1 -1  1 -1 -1]  is changed to :
 [[ 0.  2.  0.  2.  0.  0.  2.  0.]
 [ 2.  0.  0.  2.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  2. -2.  0.  2.]
 [ 2.  2.  0.  0.  0.  0.  2.  0.]
 [ 0.  0.  2.  0.  0. -2.  0.  2.]
 [ 0.  0. -2.  0. -2.  0.  0. -2.]
 [ 2.  2.  0.  2.  0.  0.  0.  0.]
 [ 0.  0.  2.  0.  2. -2.  0.  0.]]
Weight when its updated is :  [-1  1  1 -1 -1  1 -1  1]  is changed to :
 [[ 0.  1. -1.  3.  1. -1.  3. -1.]
 [ 1.  0.  1.  1. -1.  1.  1.  1.]
 [-1.  1.  0. -1.  1. -1. -1.  3.]
 [ 3.  1. -1.  0.  1. -1.  3. -1.]
 [ 1. -1.  1.  1.  0. -3.  1.  1.]
 [-1.  1. -1. -1. -3.  0. -1. -1.]
 [ 3. 